#+TITLE: Journal for the week of Sep 12th 2025
#+AUTHOR: Ben
#+DATE: 2025-09-12
#+TAGS: meta languages journal
* Quote of the Week
"Foul deeds will rise, though all the earth overwhelm them, to men's eyes."

/- Hamlet/
* Work
My manager gave me "feedback" from another manager about a project I'm working on. This project has taken longer than expected so I understand why they're unhappy about it. I'm irked that the dev I'm working with didn't being it up to me earlier. I guess it's just escalating through management, which makes sense, though I feel like I'm mature enough that I could take individual feedback and not have it affect our working relationship.

It's also tough because I've already been working evenings and weekends to get this project completed. I should've escalated to my manager earlier when I was running into issues. I thought I could figure it out and didn't think there was much my manager could do anyway, but knowing about would've helped.

* Personal
I'm reading Hamlet for fun and really enjoying it. I don't have much experience reading Shakespeare, so it has been a nice change of pace.

* Spanish
I've been practicing nightly with Duolingo. I also play soccer with a lot of people who speak Spanish but I'm nervous when speaking and put a lot of pressure on myself which causes me to forget how to say things. I have this expectation that I need to be be able to speak quickly and clearly and if not people will be annoyed with me.
