#+TITLE: Journal for the week of Jan 4th
#+AUTHOR: Ben
#+DATE: 2026-01-11
#+TAGS: languages journal learning

* Quote of the Week
"Never allow waiting to become a habit. Live your dreams and take risks. Life is happening now."

- _Paulo Coelho_

* New Year's Resolutions
I don't usually think too much about resolutions because I try not to wait to change habits. But I have a few things I want to do this year.

** 1. V1 of Shandalar 30
This is the big goal for the year. I will be really happy if I can get a functional game out by EOY. I've got a good start, but there's still so much to do. I'm using AI and it helps a lot, but it still takes time. Time to spec out how the features should work. Time to write up docs to explain to the AI how it works. And time to review/test the changes AI has made.

My book group is currently reading "Vibe Coding" so I'll try to pick up ideas to improve implementation speed.

** 2. Teach a class?
This is a maybe, I'll see how I feel after Recurse Center. Also, I'm not sure what teaching CS even looks like anymore. AI is so transformational it's hard to know how to teach programming now.

** 3. Lift and stretch regularly
Not too much in this one. I already lift and stretch occasionally, but I'd like to make it more of a habit, at least 2x/wk for lifting and 3x/wk for stretching.

** 4. See family and friends more
Depending on what I do after Recurse center I'd like to try and see people more. If I stop working it will make it easier to see my parents and grandparents.

* House Projects
I had to work a full week this week, so rude :). We picked up a small bookcase from the side of the road. It's solid wood, I would guess old growth Douglas fir or similar. It's been stained and finished, but the finish has mostly worn off the top and the shelves. I'm hoping to sand and refinish it. Rebuilding center offers a refinishing class, but there aren't any instances on their class calendar.

* Spanish
I'm not doing much Spanish practice lately. Duolingo started offering chess lessons and I've been doing that instead. Something about puzzle/problem solving is really rewarding to me compared to learning a language. I also don't make many opportunities to practice speaking, which would make Spanish more valuable to me. As it is now I really only get the joy of reading in Spanish and I'm not good enough to read anything interesting enough to hold my attention.

* Recurse Center/Shandalar 30th Anniversary Edition
I'm also looking more at housing options in New York. I've seen a few good options and am waiting to hear back from someone. Renting a single apartment is about 1.5x - 2x the cost of a shared room a house, but Andrea said she wouldn't feel comfortable visiting me otherwise. I'm not sure what I'll do after Recurse Center. After getting a beta version of Shandalar 30 out I figure it will be at least 6 months of work to get the final version out. 2027 is the 30th anniversary, so I should have something by then.
